version: "3.3"
services:
  app:
    depends_on:
      - postgresql
    build: ./
    ports:
      - "8080:8080"
  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dpd
